apiVersion: v1
kind: ConfigMap
metadata:
  name: kfp-tekton-config
data:
  artifact_bucket: "mlpipeline"
  artifact_endpoint: "minio-service.kubeflow:9000"
  artifact_endpoint_scheme: "http://"
  enable_logging: false
  enable_artifact: true
  strip_eof: false
