apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Pipeline that passes small
      constant string to to consumer", "name": "Constant to consumer pipeline"}'
    sidecar.istio.io/inject: 'false'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print-small-text": []}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/output_artifacts: '{}'
  name: constant-to-consumer-pipeline
spec:
  pipelineSpec:
    tasks:
    - name: print-small-text
      taskSpec:
        steps:
        - args:
          - --text
          - Hello world
          command:
          - python3
          - -u
          - -c
          - "def print_small_text(text):\n    '''Print small text'''\n    print(text)\n\
            \nimport argparse\n_parser = argparse.ArgumentParser(prog='Print small\
            \ text', description='Print small text')\n_parser.add_argument(\"--text\"\
            , dest=\"text\", type=str, required=True, default=argparse.SUPPRESS)\n\
            _parsed_args = vars(_parser.parse_args())\n\n_outputs = print_small_text(**_parsed_args)\n"
          image: python:3.7
          name: main
